# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-16 03:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gthockey', '0003_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='logo',
            field=models.ImageField(blank=True, upload_to='teamlogos'),
        ),
    ]
