# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-16 04:40
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('gthockey', '0005_newsstory'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsstory',
            name='date',
            field=models.DateField(default=datetime.datetime(2016, 3, 16, 4, 40, 6, 567292, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
