# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-06 13:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gthockey', '0007_auto_20160406_0932'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='score_opp_overtime',
            new_name='score_opp_ot',
        ),
    ]
