# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-04 18:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gthockey', '0009_auto_20160430_1341'),
    ]

    operations = [
        migrations.CreateModel(
            name='Board',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=25)),
                ('last_name', models.CharField(max_length=25)),
                ('position', models.CharField(max_length=25)),
                ('email', models.EmailField(max_length=100)),
                ('image', models.ImageField(upload_to='board')),
                ('description', models.CharField(max_length=1000)),
                ('priority', models.IntegerField()),
            ],
        ),
    ]
