# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-09-19 03:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gthockey', '0011_coach'),
        ('gthockey', '0010_auto_20170918_2321'),
    ]

    operations = [
    ]
