# Generated by Django 2.0.2 on 2018-03-01 09:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gthockey', '0012_merge_20170918_2323'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='season',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gthockey.Season'),
        ),
    ]
