# Generated by Django 2.0.2 on 2018-03-01 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gthockey', '0013_auto_20180301_0156'),
        ('gthockey', '0013_auto_20180301_0410'),
    ]

    operations = [
    ]
